{{ if .Values.verticalPodAutoscaler }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ template "cachenator.name" . }}
  labels:
    # These are required so recommendations show up in [t/p]-vpa/
    creator: Fairwinds
    source: goldilocks
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ template "cachenator.name" . }}
  updatePolicy:
    updateMode: {{ required ".Values.verticalPodAutoscaler.updateMode required" .Values.verticalPodAutoscaler.updateMode | quote }}
  {{- with .Values.verticalPodAutoscaler.containerPolicies }}
  resourcePolicy:
    containerPolicies: {{ toYaml . | nindent 6 }}
  {{ end }}
{{ end }}